Repository EthanThatOneKid/acmcsuf.com, pull requests merged in 2022-05, with the labels that each got.

#465 Removed `DEBUG` from parse()
  src/lib/ical/parse.ts
  src/lib/ical/utils.ts
  src/routes/events/_index.test.ts
Labels: bugfix

#469 Removed calendar emoji and replaced with blue calendar SVG
  src/routes/events/index.svelte
  static/assets/bluecalender.svg
Labels: bugfix

#472 Renamed src/routes/blog/_testdata/posts.json → posts.ts
  src/routes/blog/_index.test.ts
  src/routes/blog/_testdata/posts.json
  src/routes/blog/_testdata/posts.ts
  src/routes/blog/index.json.ts
Labels: developer experience, bugfix

#475 Events: Set up simple ICAL parser integration testing
  src/lib/ical/parse.test.ts
  src/routes/events/_testdata/events.ts
Labels: enhancement
