Repository EthanThatOneKid/acmcsuf.com, pull requests merged in 2022-10, with the labels that each got.

#603 Moved all existing routes to route group `(site)`
  src/routes/(site)/+layout.svelte
  src/routes/(site)/+page.svelte
  src/routes/(site)/1st/+page.svelte
  src/routes/(site)/[link=link].svg/+server.ts
  src/routes/(site)/about/+page.svelte
  src/routes/(site)/about/about-us.svelte
  src/routes/(site)/about/officer-profile-list.svelte
  src/routes/(site)/about/officer-profile.svelte
  src/routes/(site)/acm-paths.svelte
  src/routes/(site)/blog/+page.svelte
  src/routes/(site)/blog/+page.ts
  src/routes/(site)/blog/[id].txt/+server.ts
  src/routes/(site)/blog/[id]/+page.svelte
  src/routes/(site)/blog/[id]/+page.ts
  src/routes/(site)/blog/[id]/blog-body.svelte
  src/routes/(site)/blog/[id]/syntax-highlight.css
  src/routes/(site)/blog/[query].json/+server.ts
  src/routes/(site)/blog/labelfield.svelte
  src/routes/(site)/events/+page.svelte
  src/routes/(site)/events/+page.ts
  src/routes/(site)/events/[query].json/+server.ts
  src/routes/(site)/events/empty-container.svelte
  src/routes/(site)/events/event.svelte
  src/routes/(site)/events/list.svelte
  src/routes/(site)/feed.xml/+server.ts
  src/routes/(site)/hero.svelte
  src/routes/(site)/nodebuds/+page.svelte
  src/routes/(site)/privacy/+page.svelte
  src/routes/(site)/privacy/policy.svelte
  src/routes/(site)/quiz/+page.svelte
  src/routes/(site)/quiz/more-info.svelte
  src/routes/(site)/quiz/progress-bar.svelte
  src/routes/(site)/quiz/quiz.svelte
  src/routes/(site)/ready-up.svelte
  src/routes/(site)/teams/+page.svelte
  src/routes/(site)/teams/path-section.svelte
  src/routes/(site)/why-join.svelte
  src/routes/+layout.svelte
Labels: enhancement

#631 Add Gitcord workflow, remove legacy workflows
  .github/workflows/create_issue_channel.yaml
  .github/workflows/create_message.yaml
  .github/workflows/gitcord.yaml
  scripts/close-issue-channel.js
  scripts/common.js
  scripts/create-issue-channel.js
  scripts/create-message.js
Labels: enhancement

#640 Add interest forms and Intro to Python
  src/lib/server/links/data.ts
Labels: enhancement

#645 Shortlinks: smart resolution refactor
  src/lib/server/links/resolve.test.ts
  src/lib/server/links/resolve.ts
  src/lib/server/links/shortener.ts
  src/lib/server/links/testdata.ts
  src/lib/server/links/validate.test.ts
  src/lib/server/links/validate.ts
  src/routes/(site)/[...id=link].svg/+server.ts
Labels: enhancement

#648 Roll forward #629
  src/routes/+layout.svelte
Labels: bugfix, HIGH PRIORITY

#649 Analytics: Add Vercel Audiences
  package-lock.json
  package.json
  src/routes/+layout.svelte
Labels: enhancement

#651 Analytics: Fine-tune Vercel Audiences
  src/routes/+layout.svelte
  static/va/script.js
Labels: bugfix
