Repository EthanThatOneKid/acmcsuf.com, pull requests merged in 2022-11, with the labels that each got.

#657 Remove Vercel Audiences
  package-lock.json
  package.json
  src/routes/+layout.svelte
  static/va/script.js
Labels: bugfix

#663 Add data for Special Events team
  src/lib/public/board/data/teams.json
  src/lib/server/events/ical.ts
  static/assets/badges/special-events-team.svg
Labels: bugfix

#667 Make sure the buttons render correctly on dark mode
  static/global.css
Labels: bugfix

#674 Fix non null assertion fail in Officer profile list
  src/routes/(site)/about/officer-profile-list.svelte
Labels: bugfix

#676 Vite: using import.meta.glob over import.meta.globEager
  src/lib/public/confetti/frank.ts
  src/routes/(site)/1st/+page.svelte
Labels: bugfix

#675 Fix properties of undefined regression in results screen
  src/routes/(site)/quiz/quiz.svelte
Labels: bugfix

#677 Migrate Svelte SVGs to SVG files
  src/lib/components/bw-icon/bw-icon.svelte
  src/lib/components/footer/footer.svelte
  src/lib/components/nav/bar.svelte
  src/lib/components/svg/arrow-left.svelte
  src/lib/components/svg/arrow-right.svelte
  src/lib/server/events/ical.ts
  src/routes/(site)/about/officer-profile.svelte
  src/routes/(site)/events/event.svelte
  src/routes/(site)/quiz/quiz.svelte
  static/assets/svg/arrow-left.svg
  static/assets/svg/arrow-right.svg
  static/assets/svg/calendar-google.svg
  static/assets/svg/calendar-outlook.svg
  static/assets/svg/copy-link.svg
  static/assets/svg/discord.svg
  static/assets/svg/github.svg
  static/assets/svg/instagram.svg
  static/assets/svg/linkedin.svg
  static/assets/svg/moon.svg
  static/assets/svg/public.svg
  static/assets/svg/sun.svg
  static/assets/svg/youtube.svg
Labels: enhancement

#689 Removed the drop shadow from the blog/id pages. Issue 687
  src/routes/(site)/blog/[id]/+page.svelte
Labels: bugfix

#694 Add new November acmcsuf.com shortlinks
  src/lib/server/links/data.ts
Labels: enhancement

#705 package-lock.json hotfix
  package-lock.json
  package.json
Labels: developer experience, bugfix

#700 Switch deployment providers from Vercel to Netlify 🎉
  .env.example
  .gitignore
  GETTING_STARTED.md
  README.md
  netlify.toml
  package-lock.json
  package.json
  src/app.d.ts
  src/lib/public/analytics/types.ts
  src/lib/public/analytics/vitals.ts
  src/routes/+layout.svelte
  svelte.config.js
Labels: bugfix

#730 Redirected 404 Button to stay on the original tab.
  src/lib/components/button/button.svelte
  src/routes/(site)/hero.svelte
  src/routes/(site)/ready-up.svelte
Labels: bugfix
