Repository EthanThatOneKid/acmcsuf.com, pull requests merged in 2022-03, with the labels that each got.

#311 Added action that copies event link to clipboard
  src/lib/components/events/event-item.svelte
  src/lib/components/icons/copy-link.svelte
  src/lib/components/utils/acm-toaster.svelte
  src/lib/ical/common.ts
  src/lib/ical/parse.ts
  src/lib/stores/toasts.ts
  src/routes/__layout.svelte
  src/routes/events.json.ts
  static/global.css
Labels: enhancement

#314 Fixed button hover effect
  src/lib/components/events/event-item.svelte
Labels: bugfix

#319 Added `npm run all` 👨‍💻
  CONTRIBUTING.md
  package.json
Labels: enhancement, developer experience

#320 Update ARCHITECTURE.md
  ARCHITECTURE.md
Labels: documentation, bugfix

#321 Set up network-first service worker
  src/app.html
  src/routes/__layout.svelte
  src/service-worker.ts
  src/service-worker/common.ts
  src/service-worker/from/cache.ts
  src/service-worker/from/network.ts
  src/service-worker/index.ts
  static/manifest.json
  static/site.webmanifest
Labels: enhancement

#315 Added "copy title" action
  src/lib/components/events/event-item.svelte
  src/lib/components/icons/calendar.svelte
  src/lib/components/icons/copy-link.svelte
  src/lib/components/icons/copy-text.svelte
Labels: enhancement

#318 Events: Added "add to calendar" actions to each event item
  package-lock.json
  package.json
  src/lib/calendar-link/README.md
  src/lib/calendar-link/calendar-link.ts
  src/lib/calendar-link/index.ts
  src/lib/calendar-link/interfaces.ts
  src/lib/calendar-link/utils.ts
  src/lib/components/events/event-item.svelte
  src/lib/components/icons/google-calendar.svelte
  src/lib/components/icons/ms-office.svelte
  src/lib/components/icons/ms-outlook.svelte
  src/lib/components/icons/yahoo.svelte
  src/lib/ical/common.ts
  src/lib/ical/parse.ts
Labels: enhancement

#326 Officer List: Integrated tier-based ordering
  .github/ISSUE_TEMPLATE/officer_update_request.yaml
  package-lock.json
  package.json
  scripts/update-officer.js
  src/lib/components/about/officer-profile-list.svelte
  src/lib/components/about/officer-profile.svelte
  src/lib/constants/officers.json
  src/lib/constants/officers.ts
  src/lib/constants/tiers.json
  src/routes/about.svelte
  src/routes/blog/_query.ts
  src/routes/nodebuds.svelte
Labels: enhancement

#331 Events: Force long words to break in event item description
  src/lib/components/events/event-item.svelte
Labels: bugfix

#338 Fixing button hover effect
  src/lib/components/utils/acm-button.svelte
Labels: enhancement

#345 Events: Force long words to break in event item description pt. 2
  src/lib/components/events/event-item.svelte
Labels: bugfix

#333 Resolved annoying 'css-unused-selector' warning messages
  package-lock.json
  package.json
  src/lib/components/about/officer-profile-list.svelte
  src/lib/components/about/officer-profile.svelte
  src/lib/components/events/event-item.svelte
  src/lib/components/index/acm-paths.svelte
  src/lib/components/index/hero.svelte
  src/lib/components/index/ready-up.svelte
  src/lib/components/index/why-join.svelte
  src/lib/components/nodebuds/nodebuds-testimonial.svelte
  src/lib/components/paths/path-section.svelte
  src/lib/components/sections/call-to-action-section.svelte
  src/lib/components/sections/common-hero.svelte
  src/lib/components/sections/footer.svelte
  src/lib/components/utils/acm-button.svelte
  src/lib/components/utils/acm-empty.svelte
  src/lib/components/utils/admonition.svelte
  src/routes/about.svelte
  src/routes/blog/[id].svelte
  src/routes/blog/index.svelte
  src/routes/events.svelte
  src/routes/nodebuds.svelte
  src/routes/paths.svelte
  src/routes/privacy.svelte
  static/global.css
  static/theme.scss
Labels: enhancement, developer experience

#329 Show set amount of events on `acmcsuf.com/events` when DEBUG=1
  src/lib/constants/index.ts
  src/lib/ical/parse.ts
  src/routes/events/_index.test.ts
  src/routes/events/_testdata/events.ics
  src/routes/events/index.json.ts
Labels: enhancement, developer experience, devops

#352 Integrating dark and light mode 🎉
  src/lib/components/icons/discord.svelte
  src/lib/components/icons/github.svelte
  src/lib/components/icons/google-calendar.svelte
  src/lib/components/icons/ms-office.svelte
  src/lib/components/icons/ms-outlook.svelte
  src/lib/components/icons/yahoo.svelte
  src/lib/components/icons/youtube.svelte
  src/lib/components/sections/footer.svelte
  src/lib/components/sections/navbar.svelte
  src/lib/components/utils/acm-toggle.svelte
  src/lib/stores/theme.ts
  src/routes/__layout.svelte
  static/global.css
Labels: enhancement, help wanted

#359 1 high severity vulnerability btw
  package-lock.json
Labels: enhancement

#395 HBD AARON 👑
  src/lib/components/index/hero.svelte
  static/assets/png/hero-new.png
Labels: enhancement

#396 Darkmode: Fixed initial flash of light 📸
  src/lib/components/events/event-item.svelte
  src/lib/components/index/acm-paths.svelte
  src/lib/components/sections/navbar.svelte
  src/lib/stores/theme.ts
  src/routes/about/index.svelte
  static/global.css
Labels: enhancement, bugfix

#391 Events: Migrated custom ICAL parser from `Date` to `Temporal` API
  package-lock.json
  package.json
  src/lib/calendar-link/README.md
  src/lib/calendar-link/calendar-link.ts
  src/lib/calendar-link/index.ts
  src/lib/calendar-link/interfaces.ts
  src/lib/calendar-link/utils.ts
  src/lib/components/events/event-item.svelte
  src/lib/components/events/event-list.svelte
  src/lib/constants/index.ts
  src/lib/ical/common.ts
  src/lib/ical/index.ts
  src/lib/ical/parse.ts
  src/lib/ical/utils.test.ts
  src/lib/ical/utils.ts
  src/routes/events/_index.test.ts
  src/routes/events/index.json.ts
  src/routes/events/index.svelte
Labels: enhancement, bugfix

#353 Implemented Svelte style directive where applicable
  src/lib/components/events/event-item.svelte
  src/lib/components/index/acm-paths.svelte
  src/lib/components/paths/path-section.svelte
  src/lib/components/utils/acm-toaster.svelte
Labels: enhancement
